# Generated by Django 5.2.5 on 2025-09-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
